- name: Add some more customization
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: Set timezone to Europe/Riga
      timezone:
        name: Europe/Riga
    
    - name: Generate SSH key pair
      openssh_keypair:
        path: /home/vagrant/.ssh/id_rsa
        comment: "janis.liepins"
        group: vagrant
        owner: vagrant

