- name: Add some more customization
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: Update 'root' user .bashrc to display current Git branch
      blockinfile:
        path: /root/.bashrc
        insertafter: EOF
        block: |
          git_data() {
            if [ -d .git ]
            then
              git status 2> /dev/null | grep "working tree clean" &> /dev/null
              if [ $? -ne 0 ]; then STATUS="!"; else STATUS=""; fi
              echo -n " (`git branch 2>/dev/null | grep '^*' | colrm 1 2`$STATUS)"
            fi
          }

          export PS1="\u@\h \[\033[36m\]\w\[\033[91m\]\$(git_data) \[\033[00m\]$"

    - name: Update 'vagrant' user .bashrc to display current Git branch 
      blockinfile:
        path: /home/vagrant/.bashrc
        insertafter: EOF
        block: |
          git_data() {
            if [ -d .git ]
            then
              git status 2> /dev/null | grep "working tree clean" &> /dev/null
              if [ $? -ne 0 ]; then STATUS="!"; else STATUS=""; fi
              echo -n " (`git branch 2>/dev/null | grep '^*' | colrm 1 2`$STATUS)"
            fi
          }

          export PS1="\u@\h \[\033[36m\]\w\[\033[91m\]\$(git_data) \[\033[00m\]$"