- name: Setup Docker & Docker Compose
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  pre_tasks:
    - name: Ensure APT is updated
      apt:
        update_cache: true

  tasks:
    - name: Ensure old versions of Docker are not installed.
      package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Ensure dependencies are installed.
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools

    - name: Ensure Docker APT key is added
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository.
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        update_cache: true

    - name: Ensure Docker is installed
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Ensure Docker Python modules are installed
      pip:
        name:
          - docker
          - docker-compose

    - name: Ensure Docker service is enabled and restarted
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Ensure Docker users are added to the docker group
      user:
        name: vagrant
        groups: docker
        append: true

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
