# For reference: https://www.cyberciti.biz/faq/ubuntu-18-04-lts-set-up-openvpn-server-in-5-minutes/
- name: Install OpenVPN client
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  pre_tasks:
    - name: Ensure APT is updated
      apt:
        update_cache: true

  tasks:
    - name: Install OpenVPN client package
      apt:
        pkg:
          - openvpn
